### ISSUE TITLE
Unable to find include file in /usr/share/themes/ukui-theme/gtk-2.0/gtkrc

### ISSUE THREAD

**Issue by airycanon** [ukui/ukui-themes#1]
/usr/share/themes/ukui-theme/gtk-2.0/gtkrc:814: Unable to find include file: "apps/caja.rc"
/usr/share/themes/ukui-theme/gtk-2.0/gtkrc:816: Unable to find include file: "apps/ukuimenu.rc"

Should I comment out these two lines?

**Comment by handsome-feng** [comment]
Yes, Do you have a patch ?
