### ISSUE TITLE
Text box background mistake under light theme

### ISSUE THREAD

**Issue by vhtq18w** [ukui/ukui-themes#23]
OS: Ubuntu Kylin Focal
Vesion: <0423 build

The browser's text box background color recognition is poor under light theme.

**Reproduce**

Open a text box with a white background in Firefox. 
An example page: [Distrowatch comment](https://distrowatch.com/table.php?distribution=ubuntukylin)

![image](https://user-images.githubusercontent.com/16852919/80373178-41153600-88c7-11ea-88c7-0abf4196b935.png)

**Expected**

![image](https://user-images.githubusercontent.com/16852919/80373213-4ecabb80-88c7-11ea-996a-6add5609f379.png)

Reported by [ILYA]()
Discussion [1](https://t.me/ubuntukylin/567) and [2](https://t.me/ubuntukylin/573) on Telegram.

**Comment by kwwzzz** [comment]
have solved
![1](https://user-images.githubusercontent.com/49967540/82851285-f0c6dd80-9f31-11ea-93e4-0d29e4d89f53.png)

**Comment by kwwzzz** [comment]
![1](https://user-images.githubusercontent.com/49967540/82851508-a6922c00-9f32-11ea-9d88-a5c080c11c69.png)
have solved

**Comment by Liang-zy** [comment]
20200702 test passed
